language: c++
compiler:
- g++
before_script:
- git clone https://github.com/LucianoPC/test_node.git
- cat /etc/apt/sources.list
- sudo apt-get install libcppunit-dev g++-4.9
script:
- make run_tests
branches:
  only:
  - master
